<?php

/**
 * @file
 * Contains fourspots_login.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fourspots_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fourspots_login module.
    case 'help.page.fourspots_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User login service') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fourspots_login_theme() {
  return [
    'fourspots_login' => [
      'render element' => 'children',
    ],
  ];
}
